version: 5

dataset: default

construction:
  outDegree: [32]
  efConstruction: [100]
  neighborOverflow: [1.2f]
  addHierarchy: [Yes]
  refineFinalGraph: [Yes]
  compression:
    - type: PQ
      parameters:
        m: 192 # we can either specify the integer m or the integer mFactor. In this case, m will be set to the data dimensionality divided by mFactor
        # mFactor: 8
        # k: 256 # optional parameter. By default, k=256
        centerData: No
        anisotropicThreshold: -1.0 # optional parameter. By default, anisotropicThreshold=-1 (i.e., no anisotropy)
  reranking:
    - NVQ
  useSavedIndexIfExists: Yes

search:
  topKOverquery:
    10: [1.0, 2.0, 5.0, 10.0]
    100: [1.0, 2.0]
  useSearchPruning: [Yes]
  compression:
    - type: PQ
      parameters:
        m: 192
        # k: 256 # optional parameter. By default, k=256
        centerData: No
        anisotropicThreshold: -1.0 # optional parameter. By default, anisotropicThreshold=-1 (i.e., no anisotropy)
  benchmarks: # full option set, if the whole "benchmarks" section is not specified, a default set will be used
    throughput: [ AVG ] # additional options: [AVG, MEDIAN, MAX]
    latency: [ AVG ] # additional options: [ AVG, STD, P999 ]
    count: [ visited ] # additional options: [ visited, expanded, expanded base layer ]
    accuracy: [ recall ] # additional options: [ recall, MAP ]